open fastaseq,$ARGV[0];
#open pattern,$ARGV[1];
$pattern="CcTCcTCTTtCCGGACAacACATaCAAaGAgACCcgCcAACAGAAAaCaTAATtAGtgAACTTaTGGGAGATGTTTATAttaaattgtttctcttctatctcccatctatcttttctactattttctttagttattcactagaacaattatgactccggaagttaaatcccggggcaagtgtttctgatctaNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
";
@sequences=<fastaseq>;


	$onefile=join("",@sequences);
	@splitfile=split(">",$onefile);
	shift(@splitfile);

		for($i=0;$i<=$#splitfile;$i++)
		{
			chomp $splitfile[$i];
			@oneseqsplit=split("\n",$splitfile[$i]);
			$idseq=shift(@oneseqsplit);
			chomp $idseq;
			$idseq =~ /(^[a-zA-Z0-9_]*)/;
			$readseqid=$1;
#			print "$readseqid\n";
			$singleSeq=join("\n",@oneseqsplit);
			$singleSeq =~ s/\n//g;
			$pattern =~ s/\n//g;
			$startpos=index($singleSeq,$pattern)+1;
			$lenpattern=length($pattern);
			$endpos=$startpos+$lenpattern-1;
			print "Length::$lenpattern\nStartPosition::$startpos\nEndposition::$endpos\n";
		}
			
